Repository vanilla/vanilla, pull requests merged in 2018-05, with the labels that each got.

#7143 Add the error section CSS class to /home/updatemode
  applications/dashboard/controllers/class.homecontroller.php
Labels: Gimme!

#7139 Rename WebScraper to PageScraper
  library/Vanilla/Embeds/LinkEmbed.php
  library/Vanilla/PageScraper.php
  tests/Library/Vanilla/Embeds/EmbedManagerTest.php
  tests/Library/Vanilla/PageScraperTest.php
  tests/fixtures/src/PageScraper.php
Labels: Gimme!

#7047 Fix deprecation notice in the Vanilla Stats plugin
  plugins/VanillaStats/class.vanillastats.plugin.php
Labels: Gimme!

#7135 Check discussion view permission on a category before rendering its link
  applications/vanilla/views/discussions/helper_functions.php
  applications/vanilla/views/discussions/table_functions.php
Labels: Awaiting Feedback

#7165 Fixed the LinkedIn SVG
  applications/dashboard/design/images/authenticators/linkedin.svg
Labels: Gimme!

#7120 Add getData event to TagModule
  applications/vanilla/modules/class.tagmodule.php
Labels: Revisit

#7197 Rebuild dashboard JS
  applications/dashboard/js/app/dashboard-app.min.js
  applications/dashboard/js/app/dashboard-app.min.js.map
Labels: Gimme!

#7223 Update hard-coded descriptions of Vanilla and Porter
  applications/dashboard/models/class.updatemodel.php
Labels: Gimme!

#7222 Do not block Vanilla install for stub or swagger addons
  applications/dashboard/controllers/class.setupcontroller.php
Labels: Gimme!

#7240 Fix cached announcements on Recent Discussions sometimes being filtered out
  applications/vanilla/controllers/class.discussionscontroller.php
  applications/vanilla/models/class.discussionmodel.php
Labels: Revisit

#7256 Convert javascript tests to use headless chrome
  .npmrc
  .travis.yml
  .tslint.js
  applications/dashboard/global.d.ts
  applications/dashboard/package.json
  applications/dashboard/src/scripts/__tests__/setup.ts
  applications/dashboard/src/scripts/app/user-content/embeds/video.ts
  applications/dashboard/src/scripts/application.test.ts
  applications/dashboard/src/scripts/dom.test.ts
  applications/dashboard/src/scripts/utility.test.ts
  applications/dashboard/yarn.lock
  jest.config.js
  package.json
  tests/README.md
  tests/javascript/.babelrc
  tests/javascript/enzyme.ts
  tests/javascript/karma.conf.js
  tests/javascript/webpack.test.config.js
  tsconfig.json
  tslint.json
  webpack.config.js
  yarn.lock
Labels: Blocker
