Repository vanilla/vanilla, pull requests merged in 2018-08, with the labels that each got.

#7534 Deprecate val() function
  applications/dashboard/library/class.nestedcollection.php
  applications/dashboard/views/modules/dropdown.php
  library/core/class.dispatcher.php
  library/core/class.pluggable.php
  library/core/functions.compatibility.php
Labels: Revisit

#7543 Make editor formatting settings global in the post page
  applications/vanilla/controllers/class.vanillasettingscontroller.php
  applications/vanilla/views/vanillasettings/posting.php
  plugins/editor/addon.json
  plugins/editor/class.editor.plugin.php
Labels: Revisit

#7566 Rich Editor Theme Compatibility
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/_core-variables.scss
  applications/dashboard/scss/compatibility/_codeBlocks.scss
  applications/dashboard/scss/editor/_blockquote.scss
  applications/dashboard/scss/editor/_richEditor.scss
  applications/dashboard/scss/editor/_spoiler.scss
  applications/dashboard/scss/editor/embeds/_embedQuote.scss
  applications/dashboard/scss/editor/embeds/_embedText.scss
  applications/dashboard/src/scripts/app/user-content/embeds/quote.tsx
  themes/bittersweet/design/custom.css
Labels: WIP

#7637 Category-Following: add translation for "all"
  library/core/functions.render.php
Labels: WIP

#7639 Add Integration tests for comment drafts and modifying drafts
  tests/APIv0/SmokeTest.php
Labels: Revisit

#7657 Fix IP address not being available in tests
  tests/Bootstrap.php
Labels: Gimme!

#7659 Fix Twitter embed style
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/embeds/_embedTwitter.scss
Labels: Gimme!
