Repository vanilla/vanilla, pull requests merged in 2018-07, with the labels that each got.

#7457 Revert changes to default.master
  applications/dashboard/views/default.main.master.tpl
  applications/dashboard/views/default.master.tpl
Labels: Gimme!

#7479 Fix getStore.ts file format issue
  applications/dashboard/src/scripts/state/getStore.ts
Labels: Gimme!

#7493 Add the AfterSaveCategory event
  applications/vanilla/models/class.categorymodel.php
Labels: Backport, Backported

#7484 Fix query escaping throwing error when deleting a role
  applications/dashboard/models/class.rolemodel.php
Labels: Backport

#7498 Add the AfterCategoryDelete event
  applications/vanilla/models/class.categorymodel.php
Labels: Backport
