Repository vanilla/vanilla, pull requests merged in 2018-06, with the labels that each got.

#7299 Escape the email address in the user box
  applications/dashboard/views/modules/userbox.php
Labels: Backport

#7232 Improve README instructions for upgrades and installs for 2.6
  README.md
Labels: Backport

#7336 Rebuild
  applications/dashboard/js/admin/dashboard-bootstrap-admin.min.js
  applications/dashboard/js/admin/dashboard-bootstrap-admin.min.js.map
  applications/dashboard/js/admin/lib-dashboard-admin.min.js
  applications/dashboard/js/admin/lib-dashboard-admin.min.js.map
  applications/dashboard/js/app/dashboard-app.min.js
  applications/dashboard/js/app/dashboard-app.min.js.map
  applications/dashboard/js/app/dashboard-bootstrap-app.min.js
  applications/dashboard/js/app/dashboard-bootstrap-app.min.js.map
  applications/dashboard/js/app/lib-dashboard-app.min.js
  applications/dashboard/js/app/lib-dashboard-app.min.js.map
  applications/dashboard/js/polyfills/dashboard-polyfills.min.js.map
  applications/dashboard/manifests/admin-manifest.json
  applications/dashboard/manifests/app-manifest.json
Labels: Gimme!

#7356 Fix function name on VanillaConnectAuthenticator
  plugins/vanillaconnect/VanillaConnectAuthenticator.php
Labels: Gimme!

#7377 Add function to anonymize IP addresses
  library/core/functions.general.php
  tests/Library/Core/AnonymizeIPTest.php
Labels: Blocker

#6855 Refactor CommentModel->setWatch
  applications/vanilla/models/class.commentmodel.php
Labels: Blocker
