Repository vanilla/vanilla, pull requests merged in 2018-04, with the labels that each got.

#6920 Fix on ready handler
  src/scripts/application.js
Labels: Gimme!

#6936 Added class to back to profile button
  applications/dashboard/views/modules/profileoptions.php
Labels: Gimme!

#6934 Fix querying discussions always filtering out categories hidden from Recent Discussions
  applications/vanilla/controllers/class.discussionscontroller.php
  applications/vanilla/models/class.discussionmodel.php
  applications/vanilla/modules/class.discussionsmodule.php
Labels: Backport

#6924 Add the POST /authenticate/password endpoint
  applications/dashboard/controllers/api/AuthenticateApiController.php
  applications/dashboard/models/class.usermodel.php
  tests/APIv2/Authenticate/AuthSessionTest.php
Labels: Awaiting Feedback, Blocker

#6927 Add the POST /users/request-password endpoint
  applications/dashboard/controllers/api/UsersApiController.php
  applications/dashboard/controllers/class.entrycontroller.php
  applications/dashboard/models/class.usermodel.php
  applications/dashboard/views/entry/passwordrequest.php
  applications/dashboard/views/entry/signin.php
  tests/APIv2/AbstractAPIv2Test.php
  tests/APIv2/UsersTest.php
  tests/TestLogger.php
Labels: Blocker, Revisit

#6935 Fix bookmarking a discussion
  applications/vanilla/controllers/class.discussioncontroller.php
Labels: Backport

#6933 Rich editor emoji category shortcuts
  plugins/rich-editor/js/app/rich-editor-app.js
  plugins/rich-editor/js/app/rich-editor-app.js.map
  plugins/rich-editor/locale/en.php
  plugins/rich-editor/src/scripts/Editor/EmojiPopover.jsx
  plugins/rich-editor/src/scripts/Editor/Generic/Popover.jsx
  plugins/rich-editor/src/scripts/Editor/Generic/PopoverController.jsx
  plugins/rich-editor/src/scripts/Editor/Generic/Toolbar.jsx
  plugins/rich-editor/src/scripts/__tests__/Editor/Generic/__snapshots__/Toolbar.jsx.snap
Labels: Awaiting Feedback

#6942 Many many things!
  applications/dashboard/controllers/api/AuthenticateApiController.php
  applications/dashboard/controllers/api/AuthenticatorsApiController.php
  applications/dashboard/design/images/password-authenticator.svg
  library/Vanilla/Authenticator/Authenticator.php
  library/Vanilla/Authenticator/PasswordAuthenticator.php
  library/Vanilla/Models/AuthenticatorModel.php
  tests/APIv2/Authenticate/AuthSessionTest.php
  tests/APIv2/Authenticate/AutoConnectTest.php
  tests/APIv2/Authenticate/PasswordAuthenticatorTest.php
  tests/APIv2/AuthenticatorsTest.php
  tests/Bootstrap.php
  tests/fixtures/src/MockSSOAuthenticator.php
Labels: Blocker

#6947 Add the APIv2 client to core JS
  addon.json
  js/admin/lib-core-admin.js
  js/admin/lib-core-admin.js.map
  js/app/lib-core-app.js
  js/app/lib-core-app.js.map
  js/bootstrap-admin/core-bootstrap-admin.js
  js/bootstrap-admin/core-bootstrap-admin.js.map
  js/bootstrap-app/core-bootstrap-app.js
  js/bootstrap-app/core-bootstrap-app.js.map
  js/polyfills/core-polyfills.js
  js/polyfills/core-polyfills.js.map
  manifests/admin-manifest.json
  manifests/app-manifest.json
  src/scripts/__tests__/dom.test.js
  src/scripts/apiv2.ts
  src/scripts/bootstrap/bootstrap.js
  src/scripts/dom.ts
Labels: Blocker

#6951 [Backport] Properly set where condition if all categories are visible
  applications/vanilla/controllers/class.discussionscontroller.php
  applications/vanilla/modules/class.discussionsmodule.php
Labels: Backport

#6954 Use dependency injection in the search controller
  applications/dashboard/controllers/class.searchcontroller.php
Labels: Blocker

#6950 Update some doc blocks on Gdn_DatabaseStructure for easier autocomplete
  library/database/class.databasestructure.php
Labels: Gimme!

#6970 Fix undefined $timeLeft variable notices
  applications/vanilla/controllers/class.discussioncontroller.php
  applications/vanilla/controllers/class.postcontroller.php
  applications/vanilla/views/discussion/helper_functions.php
Labels: Bug

#6969 Fix edge case crawl errors
  applications/dashboard/modules/class.pagermodule.php
  applications/vanilla/controllers/class.categoriescontroller.php
  applications/vanilla/controllers/class.discussioncontroller.php
  applications/vanilla/controllers/class.discussionscontroller.php
  applications/vanilla/controllers/class.vanillacontroller.php
Labels: Awaiting Feedback, Needs Testing

#6977 [Backport] Remove type hinting on LogModel::deleteIDs()
  applications/dashboard/models/class.logmodel.php
Labels: Backport

#6974 Update authenticate and authenticators API
  applications/dashboard/controllers/api/AuthenticateApiController.php
  applications/dashboard/controllers/api/AuthenticatorsApiController.php
  applications/dashboard/controllers/class.authenticatecontroller.php
  applications/dashboard/controllers/class.entrycontroller.php
  library/Vanilla/Authenticator/Authenticator.php
  library/Vanilla/Authenticator/SSOAuthenticator.php
  library/Vanilla/Models/AuthenticatorModel.php
  library/core/class.auth.php
  library/core/interface.ihandshake.php
  tests/APIv2/Authenticate/AuthSessionTest.php
  tests/APIv2/Authenticate/AuthenticatorsTest.php
  tests/APIv2/Authenticate/AutoConnectTest.php
  tests/APIv2/Authenticate/InactiveAuthenticatorTest.php
  tests/APIv2/Authenticate/InvalidAuthenticatorTest.php
  tests/APIv2/Authenticate/LinkUserTest.php
  tests/APIv2/Authenticate/NoEmailTest.php
  tests/APIv2/Authenticate/PasswordAuthenticatorTest.php
  tests/APIv2/AuthenticatorsTest.php
  tests/fixtures/src/MockSSOAuthenticator.php
Labels: Blocker

#7003 [Backport] Fix timestamp default values on AccessToken table
  applications/dashboard/settings/structure.php
  library/database/class.mysqlstructure.php
Labels: Backport

#7042 Fix user search by IP never returning results
  applications/dashboard/models/class.usermodel.php
Labels: Backport

#7052 Remove the comment query tight loop
  applications/vanilla/views/discussions/table_functions.php
Labels: Backport

#6383 Accessibility - Add placeholder/title for text areas
  applications/vanilla/views/post/comment.php
  applications/vanilla/views/post/discussion.php
  applications/vanilla/views/post/editcomment.php
Labels: Revisit

#7062 Fix unnecessary discussion querying when verifying comment edit abilities
  applications/vanilla/controllers/class.discussioncontroller.php
  applications/vanilla/controllers/class.postcontroller.php
  applications/vanilla/models/class.commentmodel.php
  applications/vanilla/views/discussion/helper_functions.php
Labels: Backport

#7080 Fix filtering followed categories on deep branch
  applications/vanilla/controllers/class.categoriescontroller.php
Labels: Backport

#7083 Center linkEmbed image
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/editor/_embed.scss
Labels: Gimme!

#7091 Ignore the yarn error log
  .gitignore
Labels: Gimme!

#7090 Fix default condition in ActivityModel::canView
  applications/dashboard/models/class.activitymodel.php
Labels: Backport

#7086 Allowed symlinked plugins and applications to have javascript tests
  .eslintrc
  jest.config.js
  package.json
  src/scripts/__tests__/application.test.ts
  src/scripts/__tests__/dom.test.ts
  src/scripts/__tests__/legacy.test.js
  src/scripts/__tests__/setup.ts
  tests/fixtures/editor-rendering/embed-external-image/output-client.html
  tests/fixtures/editor-rendering/embed-external/output-client.html
  tests/fixtures/editor-rendering/embed-internal/output-client.html
  tests/fixtures/editor-rendering/embed-video/output-client.html
  webpack.config.js
  yarn.lock
Labels: Blocker

#7096 Fix casing error
  applications/dashboard/src/scripts/Authenticate/RecoverPasswordPage.tsx
Labels: Gimme!

#7101 Mark a scrape test as @large
  tests/APIv2/MediaTest.php
Labels: Gimme!
