Repository vanilla/vanilla, pull requests merged in 2018-03, with the labels that each got.

#6810 Translate the attachments upload permission
  library/Vanilla/PermissionsTranslationTrait.php
Labels: Blocker, Gimme!

#6755 Allow the index_ prefix as an alternative to get_ prefixes
  library/Garden/Web/ResourceRoute.php
  tests/Library/Garden/Web/ResourceRouteTest.php
  tests/fixtures/src/DiscussionsController.php
Labels: Blocker

#6827 Rich Editor - check upload permission
  plugins/rich-editor/class.rich-editor.plugin.php
  plugins/rich-editor/views/rich-editor.tpl
Labels: Gimme!

#6830 Remove console.log in test
  src/scripts/__tests__/legacy.test.js
Labels: Gimme!

#6833 Removed explicit width on .selectBox-link
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/new-features/selectBox.scss
Labels: Gimme!

#6857 Added common class to discussion filter and discussion sort.
  applications/vanilla/views/modules/discussionssortfilter.php
Labels: Gimme!

#6866 Rich editor - Improve menu accessibility
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/new-features/_richEditor.scss
  plugins/rich-editor/locale/en.php
  plugins/rich-editor/src/scripts/__tests__/components/EditorMenuItem.test.jsx
  plugins/rich-editor/src/scripts/__tests__/components/__snapshots__/EditorMenuItem.test.jsx.snap
  plugins/rich-editor/src/scripts/__tests__/components/__snapshots__/EditorToolbar.test.jsx.snap
  plugins/rich-editor/src/scripts/components/EditorMenuItem.jsx
  plugins/rich-editor/src/scripts/components/EditorProvider.jsx
  plugins/rich-editor/src/scripts/components/EditorToolbar.jsx
  plugins/rich-editor/src/scripts/components/EmbedPopover.jsx
  plugins/rich-editor/src/scripts/components/EmojiPicker.jsx
  plugins/rich-editor/src/scripts/components/EmojiPopover.jsx
  plugins/rich-editor/src/scripts/components/InlineEditorToolbar.jsx
  plugins/rich-editor/src/scripts/components/ParagraphEditorToolbar.jsx
  plugins/rich-editor/src/scripts/components/Popover.jsx
  plugins/rich-editor/src/scripts/components/PopoverController.jsx
  plugins/rich-editor/src/scripts/components/SelectionPositionToolbar.jsx
  plugins/rich-editor/views/rich-editor.tpl
  plugins/rich-editor/views/richeditorstyles/index.php
Labels: Needs Testing

#6865 Allow react components to mount on pages
  addon.json
  js/admin/lib-core-admin.js
  js/admin/lib-core-admin.js.map
  js/app/lib-core-app.js
  js/app/lib-core-app.js.map
  js/bootstrap-admin/core-bootstrap-admin.js
  js/bootstrap-admin/core-bootstrap-admin.js.map
  js/bootstrap-app/core-bootstrap-app.js
  js/bootstrap-app/core-bootstrap-app.js.map
  js/chunk/polyfill-bootstrap-admin.js
  js/chunk/polyfill-bootstrap-admin.js.map
  js/chunk/polyfill-bootstrap-app.js
  js/chunk/polyfill-bootstrap-app.js.map
  js/global.js
  library/core/class.controller.php
  manifests/admin-manifest.json
  manifests/app-manifest.json
  package.json
  resources/views/react.php
  src/scripts/Components/DocumentTitle.jsx
  src/scripts/Main/App.jsx
  src/scripts/Main/NotFoundPage.jsx
  src/scripts/__tests__/application.test.js
  src/scripts/__tests__/utility.test.js
  src/scripts/application.js
  src/scripts/bootstrap/bootstrap.js
  src/scripts/events.js
  src/scripts/gdn.js
  src/scripts/internal.jsx
  src/scripts/utility.js
  webpack.config.js
  yarn.lock
Labels: WIP

#6891 Revert "Remove new unused javascript from the release"
  library/core/class.controller.php
Labels: Hold

#6923 Catch a wider variety of errors when generating OpenAPI docs
  applications/dashboard/controllers/api/OpenApiApiController.php
  applications/dashboard/models/ReflectionAction.php
Labels: Gimme!
