Repository vanilla/vanilla, pull requests merged in 2018-09, with the labels that each got.

#7722 New variables for KB
  applications/dashboard/scss/_core-variables.scss
Labels: Gimme!

#7730 Messages UI improvements
  applications/dashboard/controllers/class.messagecontroller.php
Labels: Gimme!

#7714 Remove nonexistent CSS file from search controller
  applications/dashboard/controllers/class.searchcontroller.php
Labels: Gimme!

#7233 Changing file_get_contents in getProfile() to cURL
  plugins/Facebook/class.facebook.plugin.php
Labels: Revisit

#7765 Update vanilla standards version
  composer.json
  composer.lock
Labels: Gimme!

#7752 Update class.database.php misspelling
  library/database/class.database.php
Labels: Gimme!

#7784 Add config toggle to Vanilla\Utility\Deprecation::log
  library/Vanilla/Utility/Deprecation.php
  library/core/functions.general.php
Labels: Revisit

#7753 Update class.databasestructure.php misspelling
  library/database/class.databasestructure.php
Labels: Gimme!

#7798 Put imports behind a feature flag and harden custom import paths
  applications/dashboard/controllers/class.importcontroller.php
  applications/dashboard/settings/class.hooks.php
Labels: Backport

#7806 Only allow http/https in ProxyRequest
  library/core/class.proxyrequest.php
Labels: Backport

#7799 Add the string ‘rapidminer’ as an acceptable scheme to be output as HTML
  library/core/class.vanillahtmlformatter.php
Labels: Backport

#7805 Fix the absoluteSource() function
  library/core/functions.general.php
  tests/Library/Core/GeneralFunctionsTest.php
Labels: Backport
