Repository vanilla/vanilla, pull requests merged in 2018-02, with the labels that each got.

#6614 Rich Editor - Minor fixes to spacing in embedded links
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/new-features/_embed.scss
Labels: Gimme!

#6585 Fix dba/counts overwriting Category.LastDiscussionID with older discussion
  applications/vanilla/models/class.categorymodel.php
Labels: Backport

#6637 Refactor sort and filter UI for ideation
  applications/dashboard/scss/compatibility/_mixins.scss
  applications/dashboard/scss/compatibility/_utilities.scss
  applications/dashboard/scss/new-features/selectBox.scss
  applications/dashboard/scss/style-compat.scss
  applications/vanilla/models/class.discussionmodel.php
  applications/vanilla/modules/class.discussionssortfiltermodule.php
  applications/vanilla/views/modules/discussionssortfilter.php
  library/core/functions.render.php
Labels: Awaiting Feedback

#6705 Allow to get the list of current handlers from the event manager
  library/Garden/EventManager.php
Labels: Gimme!
