Repository vanilla/vanilla, pull requests merged in 2019-04, with the labels that each got.

#8619 Add support for pasting images into Rich Editor
  plugins/rich-editor/src/scripts/@types/quill.d.ts
  plugins/rich-editor/src/scripts/__tests__/OpUtils.ts
  plugins/rich-editor/src/scripts/__tests__/quillUtils.ts
  plugins/rich-editor/src/scripts/quill/ClipboardModule.test.ts
  plugins/rich-editor/src/scripts/quill/ClipboardModule.ts
  plugins/rich-editor/src/scripts/quill/Formatter.test.ts
  plugins/rich-editor/src/scripts/quill/blots/blocks/ListBlot.test.ts
  plugins/rich-editor/src/scripts/quill/blots/blocks/ListBlot.ts
Labels: Status: Hold

#8624 Deprecate ApplicationManager, ThemeManager, PluginManager, PluginManager, Pluggable
  library/core/class.applicationmanager.php
  library/core/class.gdn.php
  library/core/class.pluggable.php
  library/core/class.pluginmanager.php
  library/core/class.thememanager.php
Labels: Release: Deprecate

#8535 Fix regression disabling of categories
  library/core/class.form.php
Labels: Status: Needs Backport

#8659 Fix imgur embeds
  library/Vanilla/Formatting/Embeds/ImgurEmbed.php
Labels: Domain: Rich Editor, Type: Bug

#8634 Make pagination more accessible
  applications/dashboard/modules/class.pagermodule.php
Labels: Release: Deprecate

#8700 Fix broken link to Google Sign In settings page.
  plugins/googlesignin/addon.json
Labels: Quickie, Status: Needs Backport

#8701 Styles for mobile dropdown with drafts/revisions
  library/src/scripts/flyouts/DropDown.tsx
  library/src/scripts/flyouts/dropDownStyles.ts
  library/src/scripts/headers/VanillaHeader.tsx
  library/src/scripts/headers/pieces/MobileDropDown.tsx
  library/src/scripts/headers/pieces/mobileDropDownStyles.ts
  library/src/scripts/icons/common.tsx
  library/src/scripts/layout/PanelLayout.tsx
  library/src/scripts/layout/frame/frameStyles.ts
  library/src/scripts/layout/panelLayoutStyles.ts
  library/src/scripts/modal/Modal.tsx
  library/src/scripts/modal/modalStyles.ts
  library/src/scripts/navigation/CloseButton.tsx
  library/src/scripts/navigation/siteNavAdminLinksStyles.ts
  library/src/scripts/splash/splashStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/metasStyles.ts
  library/src/scripts/styles/styleHelpers.ts
  library/src/scss/layouts/_panelLayout.scss
  library/src/scss/layouts/_panelWidget.scss
  package.json
  yarn.lock
Labels: Priority: Blocker

#8720 Fix some SiteNav styling issues
  library/src/scripts/layout/panelLayoutStyles.ts
  library/src/scripts/loaders/loaderStyles.ts
  library/src/scripts/navigation/SiteNav.tsx
  library/src/scripts/navigation/SiteNavContext.tsx
  library/src/scripts/navigation/SiteNavNode.tsx
  library/src/scripts/navigation/siteNavAdminLinksStyles.ts
  library/src/scripts/navigation/siteNavStyles.ts
  library/src/scripts/styles/styleHelpers.ts
  yarn.lock
Labels: Priority: Blocker

#8718 Fix url links transformation when app is installed in subfolder
  library/src/scripts/routing/links/LinkContextProvider.tsx
  library/src/scripts/utility/appUtils.tsx
Labels: Priority: Blocker

#8729 Fixed text input styles for iOS devices
  library/src/scripts/forms/inputStyles.tsx
  library/src/scripts/styles/styleHelpers.ts
  plugins/rich-editor/src/scripts/editor/richEditorFormClasses.ts
Labels: Priority: Blocker

#8744 Add support for robots.txt
  applications/dashboard/controllers/RobotsController.php
  applications/dashboard/settings/structure.php
  applications/dashboard/views/robots/index.twig
Labels: Priority: Blocker
