Repository vanilla/vanilla, pull requests merged in 2019-02, with the labels that each got.

#8277 Transfer Akismet plugin to Vanilla from addons
  plugins/Akismet/LICENSE.md
  plugins/Akismet/addon.json
  plugins/Akismet/akismet.png
  plugins/Akismet/class.akismet.php
  plugins/Akismet/class.akismet.plugin.php
  plugins/Akismet/class.socketwriteread.php
Labels: Status: Hold, Type: Chore

#8325 Fix users/me endpoint for Admin=2 users
  applications/dashboard/controllers/api/UsersApiController.php
Labels: Status: Needs Backport

#8335 Fix mobile input default being Rich when addon disabled
  applications/dashboard/settings/structure.php
Labels: Status: Needs Backport

#8354 Add foundation for reactions
  applications/dashboard/settings/structure.php
  library/Vanilla/Models/ReactionModel.php
Labels: Priority: Blocker

#8398 Reported Posts: fix reported activity posts displaying as html
  library/core/functions.general.php
Labels: Type: Bug

#8382 Migrate to static OpenAPI definitions
  .travis.yml
  applications/conversations/openapi/conversations.yml
  applications/conversations/openapi/messages.yml
  applications/dashboard/controllers/api/OpenApiApiController.php
  applications/dashboard/openapi/addons.yml
  applications/dashboard/openapi/dashboard.yml
  applications/dashboard/openapi/drafts.yml
  applications/dashboard/openapi/locales.yml
  applications/dashboard/openapi/media.yml
  applications/dashboard/openapi/notifications.yml
  applications/dashboard/openapi/rich.yml
  applications/dashboard/openapi/roles.yml
  applications/dashboard/openapi/schemas.yml
  applications/dashboard/openapi/search.yml
  applications/dashboard/openapi/tokens.yml
  applications/dashboard/openapi/users.yml
  applications/vanilla/openapi/categories.yml
  applications/vanilla/openapi/comments.yml
  applications/vanilla/openapi/discussions.yml
  library/Vanilla/OpenAPIBuilder.php
  library/setup/ComposerHelper.php
  package.json
  plugins/swagger-ui/addon.json
  plugins/swagger-ui/src/scripts/mountSwagger.ts
  plugins/swagger-ui/src/scss/swagger-ui.scss
  tests/Library/Vanilla/OpenAPIBuilderTest.php
  tests/fixtures/error-index.php
  tests/fixtures/error.php
  yarn.lock
Labels: Type: Enhancement
