Repository vanilla/vanilla, pull requests merged in 2019-10, with the labels that each got.

#9386 Allow truly dynamic redux reducers
  library/src/scripts/redux/getStore.ts
  library/src/scripts/redux/reducerRegistry.ts
  library/src/scripts/styles/styleUtils.ts
  library/src/scripts/theming/getThemeVariables.ts
  library/src/scripts/theming/loadThemeFonts.ts
Labels: Priority: Blocker

#9387 Implement locale utilities using /api/v2/locales endpoint in @vanilla/i18n package
  library/package.json
  library/src/scripts/AppContext.tsx
  library/src/scripts/bootstrap.ts
  library/src/scripts/locales/localeActions.ts
  library/src/scripts/locales/localeBootstrap.ts
  library/src/scripts/locales/localeReducer.ts
  library/src/scripts/redux/reducerRegistry.ts
  library/src/scripts/utility/appUtils.test.ts
  library/src/scripts/utility/appUtils.tsx
  packages/vanilla-i18n/package.json
  packages/vanilla-i18n/src/LocaleDisplayer.tsx
  packages/vanilla-i18n/src/LocaleProvider.tsx
  packages/vanilla-i18n/src/index.ts
  packages/vanilla-i18n/src/localeStore.ts
  packages/vanilla-i18n/src/translationStore.test.ts
  packages/vanilla-i18n/src/translationStore.ts
  packages/vanilla-i18n/tsconfig.json
Labels: Priority: Blocker

#9382 Use label instead of title in user fragment
  library/Vanilla/Models/UserFragmentSchema.php
  library/src/scripts/@types/api/users.ts
  library/src/scripts/content/UserLabel.tsx
  library/src/scripts/embeddedContent/QuoteEmbed.story.tsx
Labels: Status: Needs Backport

#9400 Check infrastructure sphinx index template to be enabled
  library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php
Labels: Status: Needs Backport, Status: WIP

#9405 Implement `getForSectionGroup()` in MockSiteSectionProvider
  tests/fixtures/src/MockSiteSectionProvider.php
Labels: Priority: Blocker

#9419 Remove logging for empty config keys
  library/core/class.configuration.php
  tests/Library/Core/GdnConfigurationTest.php
Labels: Priority: Blocker

#9421 Fix session stash not having a sessionID.
  library/core/class.session.php
Labels: Type: Bug

#9423 Make syntax highlighting more robust
  library/src/scripts/content/UserContent.tsx
  library/src/scripts/content/code.ts
  library/src/scripts/content/hashScrolling.ts
  plugins/rich-editor/src/scripts/editor/EditorContent.tsx
  plugins/rich-editor/src/scripts/quill/blots/blocks/CodeBlockBlot.ts
Labels: Status: Needs Backport

#9430 Fix translations not loading in frontend
  library/src/scripts/locales/localeBootstrap.ts
Labels: Status: Needs Backport

#9432 Extend mockSiteSectionProvider to provide 2 siteSectionGroups
  library/Vanilla/Contracts/Site/SiteSectionProviderInterface.php
  library/core/class.request.php
  tests/Bootstrap.php
  tests/fixtures/src/MockSiteSectionProvider.php
Labels: Status: WIP

#9455 Improve SiteSection and MockSiteSectionProvider for tests
  library/Vanilla/Models/SiteMeta.php
  library/Vanilla/Models/ThemePreloadProvider.php
  tests/Bootstrap.php
  tests/fixtures/src/MockSiteSectionProvider.php
Labels: Priority: Blocker

#9504 Add pluggable search filter context provider
  library/src/scripts/AppContext.tsx
  library/src/scripts/contexts/SearchFilterContext.tsx
  library/src/scripts/forms/select/SelectOne.tsx
Labels: Priority: Blocker

#9503 Set Google+ plugin to hidden
  plugins/GooglePlus/addon.json
  tests/APIv2/AddonsTest.php
Labels: Status: WIP
