Repository vanilla/vanilla, pull requests merged in 2019-09, with the labels that each got.

#9250 Fix emoji suggestions not displaying
  applications/dashboard/settings/class.hooks.php
  library/core/class.emoji.php
Labels: Status: Needs Backport

#9275 Bump composer dependencies (particularly garden-container)
  composer.json
  composer.lock
Labels: Priority: Blocker

#9281 Improve twig utilities
  applications/vanilla/views/vanillasettings/editcategory.php
  bootstrap.php
  library/Garden/TwigTrait.php
  library/Vanilla/Utility/HtmlUtils.php
  library/Vanilla/Web/LegacyTwigViewHandler.php
  library/Vanilla/Web/TwigEnhancer.php
  library/Vanilla/Web/TwigFormWrapper.php
  library/Vanilla/Web/TwigRenderTrait.php
  library/Vanilla/Web/TwigStaticRenderer.php
  tests/Bootstrap.php
  tests/fixtures/src/MockAddonProvider.php
Labels: Priority: Blocker

#9313 Add getCurrent to site section provider
  library/Vanilla/Contracts/Site/SiteSectionProviderInterface.php
  library/Vanilla/Site/SingleSiteSectionProvider.php
Labels: Priority: Blocker

#9336 Fix storybook rendering consistency
  applications/dashboard/src/scripts/__tests__/dashboardCssDecorator.tsx
  build/.storybook/addons.js
  build/.storybook/config.js
  library/src/scripts/features/search/IndependentSearch.tsx
  library/src/scripts/routing/links/SmartLink.tsx
  library/src/scripts/storybook/StoryContent.tsx
  library/src/scripts/utility/idUtils.ts
  package.json
  yarn.lock
Labels: Priority: Blocker

#9327 Add advanced search record type interfaces to the core
  library/Vanilla/Contracts/Search/SearchRecordTypeInterface.php
  library/Vanilla/Contracts/Search/SearchRecordTypeProviderInterface.php
  library/Vanilla/Contracts/Search/SearchRecordTypeTrait.php
  library/Vanilla/Navigation/BreadcrumbModel.php
Labels: Status: WIP
