Repository vanilla/vanilla, pull requests merged in 2019-03, with the labels that each got.

#8479 Fix legacy script order in GDN controller
  library/core/class.controller.php
Labels: Release: Transitive

#8489 Theming Vars - Splash (WIP), body, dropdowns, frames, Header
  library/src/scripts/application.tsx
  library/src/scripts/components/IndependentSearch.tsx
  library/src/scripts/components/body/Backgrounds.tsx
  library/src/scripts/components/dropdown/DropDown.tsx
  library/src/scripts/components/forms/formElementStyles.ts
  library/src/scripts/components/frame/Frame.tsx
  library/src/scripts/components/frame/FrameBody.tsx
  library/src/scripts/components/frame/FrameFooter.tsx
  library/src/scripts/components/frame/FrameHeader.tsx
  library/src/scripts/components/frame/FrameHeaderWithAction.tsx
  library/src/scripts/components/frame/FramePanel.tsx
  library/src/scripts/components/headers/VanillaHeader.tsx
  library/src/scripts/components/headers/pieces/MobileDropDown.tsx
  library/src/scripts/components/mebox/pieces/CompactSearch.tsx
  library/src/scripts/components/mebox/pieces/MeBoxDropDownItemList.tsx
  library/src/scripts/components/mebox/pieces/NotificationsContents.tsx
  library/src/scripts/components/modal/ModalConfirm.tsx
  library/src/scripts/components/splash/Splash.tsx
  library/src/scripts/styles/bodyStyles.ts
  library/src/scripts/styles/buttonStyles.ts
  library/src/scripts/styles/frameStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/loaderStyles.ts
  library/src/scripts/styles/meBoxMessageStyles.ts
  library/src/scripts/styles/navLinksStyles.ts
  library/src/scripts/styles/searchBarStyles.ts
  library/src/scripts/styles/splashStyles.ts
  library/src/scripts/styles/styleHelpers.ts
  library/src/scripts/styles/subcommunityTitleStyles.ts
  library/src/scripts/styles/vanillaHeaderStyles.ts
  library/src/scripts/styles/widgetStyleVars.ts
  library/src/scripts/theming/ThemeProvider.tsx
  library/src/scss/_coreVariables.scss
  library/src/scss/layouts/_frame.scss
  plugins/rich-editor/src/scripts/styles/richEditorStyles/richEditorFormClasses.ts
Labels: Status: WIP

#8509 Add index to GDN_Comment.Score
  applications/vanilla/settings/structure.php
Labels: Type: Enhancement

#8492 Fix invalid rich posts being created while uploads are in-progress
  library/Vanilla/Formatting/Formats/RichFormat.php
  library/Vanilla/Formatting/Quill/Filterer.php
  tests/APIv0/Controllers/ModerationControllerTest.php
  tests/APIv0/SmokeTest.php
  tests/Library/Core/ValidationTest.php
  tests/Library/Vanilla/Formatting/Quill/FiltererTest.php
Labels: Domain: Rich Editor, Type: Bug

#8540 Fix filterer regression and add test case
  library/Vanilla/Formatting/Quill/Filterer.php
  tests/Library/Vanilla/Formatting/Quill/FiltererTest.php
Labels: Release: Transitive

#8554 Fix keystone mobile logo alignment
  themes/keystone/design/custom_cerulean.css
  themes/keystone/design/custom_cerulean.css.map
  themes/keystone/design/custom_classic.css
  themes/keystone/design/custom_classic.css.map
  themes/keystone/design/custom_coral.css
  themes/keystone/design/custom_coral.css.map
  themes/keystone/design/custom_dark.css
  themes/keystone/design/custom_dark.css.map
  themes/keystone/design/custom_default.css
  themes/keystone/design/custom_default.css.map
  themes/keystone/design/custom_dusk.css
  themes/keystone/design/custom_dusk.css.map
  themes/theme-boilerplate/design/custom.css
  themes/theme-boilerplate/design/custom.css.map
  themes/theme-boilerplate/package.json
  themes/theme-boilerplate/src/scss/sections/_header.scss
Labels: Status: Needs Backport

#8571 Upgrade PHP version requirements to 7.1
  composer.json
  composer.lock
  conf/constants.php
  environment.php
Labels: Release: BC Break, Type: Enhancement
