Repository vanilla/vanilla, pull requests merged in 2019-01, with the labels that each got.

#8163 Fix CategoryModel::getAll references to nonexistent parameters
  applications/vanilla/controllers/class.vanillasettingscontroller.php
  applications/vanilla/models/class.categorymodel.php
Labels: Gimme!

#8164 Add extra CSS class for remember password
  applications/dashboard/views/entry/signin.php
Labels: Gimme!

#8202 Implement rich attachments for comments & discussions
  applications/dashboard/controllers/api/MediaApiController.php
  applications/dashboard/settings/structure.php
  applications/vanilla/models/class.commentmodel.php
  applications/vanilla/models/class.discussionmodel.php
  bootstrap.php
  library/Garden/TwigTrait.php
  library/Vanilla/BodyFormatValidator.php
  library/Vanilla/Contracts/Formatting/FormatInterface.php
  library/Vanilla/Formatting/Attachment.php
  library/Vanilla/Formatting/BaseFormat.php
  library/Vanilla/Formatting/Embeds/Embed.php
  library/Vanilla/Formatting/Embeds/EmbedManager.php
  library/Vanilla/Formatting/Embeds/FileEmbed.php
  library/Vanilla/Formatting/Embeds/GettyEmbed.php
  library/Vanilla/Formatting/Embeds/GiphyEmbed.php
  library/Vanilla/Formatting/Embeds/ImgurEmbed.php
  library/Vanilla/Formatting/Embeds/InstagramEmbed.php
  library/Vanilla/Formatting/Exception/FormatterNotFoundException.php
  library/Vanilla/Formatting/Exception/FormattingException.php
  library/Vanilla/Formatting/FormatService.php
  library/Vanilla/Formatting/Formats/RichFormat.php
  library/Vanilla/Formatting/Heading.php
  library/Vanilla/Formatting/Quill/BlotGroupCollection.php
  library/Vanilla/Formatting/Quill/Blots/Embeds/ExternalBlot.php
  library/Vanilla/Formatting/Quill/Blots/Lines/HeadingTerminatorBlot.php
  library/Vanilla/Formatting/Quill/Filterer.php
  library/Vanilla/Formatting/Quill/Parser.php
  library/Vanilla/Formatting/UpdateMediaTrait.php
  library/Vanilla/Web/LegacyTwigViewHandler.php
  library/Vanilla/Web/TwigRenderTrait.php
  library/core/class.format.php
  library/src/scripts/apiv2.ts
  library/src/scripts/dom.ts
  library/src/scripts/embeds.tsx
  library/src/scripts/user-content/embeds/file.tsx
  library/src/scripts/user-content/index.ts
  plugins/rich-editor/src/scripts/components/editor/pieces/EditorUploadButton.tsx
  plugins/rich-editor/src/scripts/quill/EmbedInsertionModule.ts
  plugins/rich-editor/src/scripts/quill/blots/embeds/ExternalEmbedBlot.ts
  resources/views/userContentError.twig
  tests/Bootstrap.php
  tests/Library/Core/ValidationTest.php
  tests/SharedBootstrapTestCase.php
Labels: DB Update

#8173 Transfer the pockets plugin from the addons repo
  .gitignore
  plugins/pockets/LICENSE.md
  plugins/pockets/PocketsPlugin.php
  plugins/pockets/addon.json
  plugins/pockets/design/pockets.css
  plugins/pockets/icon.png
  plugins/pockets/js/pockets.js
  plugins/pockets/library/Pocket.php
  plugins/pockets/locale/en.php
  plugins/pockets/pocket.png
  plugins/pockets/views/addedit.php
  plugins/pockets/views/delete.php
  plugins/pockets/views/index.php
Labels: Chore, Hold

#8172 Transfer the hero image plugin from the internal repo
  plugins/heroimage/.editorconfig
  plugins/heroimage/README.md
  plugins/heroimage/SmartyPlugins/function.hero_image_link.php
  plugins/heroimage/addon.json
  plugins/heroimage/class.heroimage.plugin.php
  plugins/heroimage/hero_image.png
Labels: Chore, Hold

#8166 Throw a deprecation warning when using Gdn_SQLDriver::whereNotIn with empty arrays
  library/database/class.sqldriver.php
Labels: Deprecate

#8216 Add form border radius to forum rich editor focus state
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/compatibility/editor/_richEditorLegacy.scss
Labels: Domain: Rich Editor, Domain: UI

#8013 Update Phing build with more exclusions
  build/package-include.txt
Labels: WIP

#8242 Add additional unit tests & test coverage to Gdn_Format
  library/core/class.format.php
  library/core/functions.general.php
  phpunit.xml.dist
  tests/Bootstrap.php
  tests/Library/Vanilla/Formatting/AssertsFixtureRenderingTrait.php
  tests/Library/Vanilla/Formatting/GdnFormatLinksTest.php
  tests/Library/Vanilla/Formatting/GdnFormatTest.php
  tests/Library/Vanilla/Formatting/Quill/RendererTest.php
  tests/fixtures/formats/bbcode/html/block-formatting/output.txt
  tests/fixtures/formats/bbcode/html/embeds/output.txt
  tests/fixtures/formats/bbcode/html/inline-formatting/output.txt
  tests/fixtures/formats/bbcode/html/paragraphs/output.txt
  tests/fixtures/formats/bbcode/html/xss/output.txt
  tests/fixtures/formats/html/html/inline-formatting/output.txt
  tests/fixtures/formats/html/html/paragraph-formats/input.html
  tests/fixtures/formats/html/html/paragraph-formats/output.html
  tests/fixtures/formats/html/html/paragraph-formats/output.txt
  tests/fixtures/formats/html/html/paragraphs/output.txt
  tests/fixtures/formats/html/html/xss/output.txt
  tests/fixtures/formats/markdown/html/inline-formatting/output.txt
  tests/fixtures/formats/markdown/html/paragraph-formatting/input.md
  tests/fixtures/formats/markdown/html/paragraph-formatting/output.html
  tests/fixtures/formats/markdown/html/paragraph-formatting/output.txt
  tests/fixtures/formats/markdown/html/paragraphs/output.txt
  tests/fixtures/formats/markdown/html/xss/output.txt
  tests/fixtures/formats/text/html/paragraphs/output.txt
  tests/fixtures/formats/text/html/xss/output.txt
  tests/fixtures/formats/textex/html/formatting/output.txt
  tests/fixtures/formats/textex/html/paragraphs/input.txt
  tests/fixtures/formats/textex/html/paragraphs/output.html
  tests/fixtures/formats/textex/html/paragraphs/output.txt
  tests/fixtures/formats/textex/html/xss/output.txt
  tests/fixtures/formats/wysiwyg/html/inline-formatting/output.txt
  tests/fixtures/formats/wysiwyg/html/paragraph-formats/input.html
  tests/fixtures/formats/wysiwyg/html/paragraph-formats/output.html
  tests/fixtures/formats/wysiwyg/html/paragraph-formats/output.txt
  tests/fixtures/formats/wysiwyg/html/paragraphs/output.txt
  tests/fixtures/formats/wysiwyg/html/xss/output.txt
  tests/fixtures/src/MockConfig.php
Labels: Release: BC Break
