Repository vanilla/vanilla, pull requests merged in 2019-05, with the labels that each got.

#8766 Fix inconsistencies in Panel Layout and convert its styles to JS
  library/src/scripts/features/search/searchBarStyles.ts
  library/src/scripts/features/subcommunities/subcommunityListStyles.ts
  library/src/scripts/flyouts/DropDown.tsx
  library/src/scripts/flyouts/dropDownStyles.ts
  library/src/scripts/forms/formElementStyles.ts
  library/src/scripts/forms/radioTabs/radioTabStyles.ts
  library/src/scripts/headers/TitleBar.tsx
  library/src/scripts/headers/TitleBarHome.tsx
  library/src/scripts/headers/mebox/pieces/MessagesContents.tsx
  library/src/scripts/headers/mebox/pieces/NotificationsContents.tsx
  library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
  library/src/scripts/headers/mebox/pieces/meBoxStyles.ts
  library/src/scripts/headers/pieces/mobileDropDownStyles.ts
  library/src/scripts/headers/titleBarNavStyles.ts
  library/src/scripts/headers/titleBarStyles.ts
  library/src/scripts/headers/vanillaHeaderStyles.ts
  library/src/scripts/layout/DeviceContext.tsx
  library/src/scripts/layout/Heading.tsx
  library/src/scripts/layout/PanelLayout.tsx
  library/src/scripts/layout/bodyStyles.ts
  library/src/scripts/layout/components/containerStyles.ts
  library/src/scripts/layout/components/widgetContainerStyles.ts
  library/src/scripts/layout/deviceCheckerStyles.tsx
  library/src/scripts/layout/layoutStyles.ts
  library/src/scripts/layout/panelAreaStyles.ts
  library/src/scripts/layout/panelLayoutStyles.ts
  library/src/scripts/layout/panelListStyles.ts
  library/src/scripts/layout/panelWidgetStyles.ts
  library/src/scripts/messages/messageStyles.ts
  library/src/scripts/modal/modalStyles.ts
  library/src/scripts/navigation/navLinksStyles.ts
  library/src/scripts/navigation/siteNavStyles.ts
  library/src/scripts/routing/links/backLinkStyles.ts
  library/src/scripts/splash/Splash.tsx
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/styleHelpers.ts
  library/src/scripts/styles/textUtils.ts
  library/src/scripts/styles/typographyStyles.ts
  library/src/scss/_base.scss
  library/src/scss/layouts/_deviceChecker.scss
  library/src/scss/layouts/_page.scss
  library/src/scss/layouts/_panelArea.scss
  library/src/scss/layouts/_panelLayout.scss
  library/src/scss/layouts/_panelWidget.scss
  library/src/scss/utility/_typography.scss
  package.json
  plugins/rich-editor/src/scripts/editor/EditorParagraphMenu.tsx
  plugins/rich-editor/src/scripts/editor/context.tsx
  plugins/rich-editor/src/scripts/editor/richEditorFormClasses.ts
  yarn.lock
Labels: Priority: Blocker

#8772 A config override for relative/absolute path in setCacheDir
  library/Vanilla/AddonManager.php
Labels: Status: Needs Backport

#8781 KB Added container component to max out the width of the banner
  library/src/scripts/messages/Message.tsx
Labels: Priority: Blocker

#8778 KB - Fixed visual issues with search page
  library/src/scripts/features/search/searchResultsStyles.ts
  library/src/scripts/forms/buttonStyles.ts
  library/src/scripts/headers/pieces/mobileDropDownStyles.ts
  library/src/scripts/layout/PageHeading.tsx
  library/src/scripts/layout/PanelLayout.tsx
  library/src/scripts/layout/pageHeadingStyles.tsx
  library/src/scripts/navigation/SimplePager.tsx
  library/src/scripts/navigation/simplePagerStyles.ts
  library/src/scripts/result/Result.tsx
  library/src/scripts/routing/links/BackLink.tsx
  library/src/scripts/routing/links/backLinkStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/textUtils.ts
  library/src/scripts/styles/typographyStyles.ts
Labels: Priority: Blocker

#8787 Add support for React-based input validation in existing forms
  library/src/scripts/bootstrap.ts
  library/src/scripts/dom/domUtils.tsx
  library/src/scripts/forms/TextInput.tsx
  library/src/scripts/forms/mountInputs.tsx
  library/src/scripts/utility/utils.ts
Labels: Priority: Blocker

#8767 Embedded Comments - Inherit dashboard post format type
  applications/vanilla/views/discussion/embed.php
  applications/vanilla/views/discussion/helper_functions.php
  plugins/rich-editor/RichEditorPlugin.php
Labels: Status: Needs Backport

#8839 Line Height Fix and Splitting "frame" styles into multiple files.
  library/src/scripts/content/userContentStyles.ts
  library/src/scripts/features/search/searchBarStyles.ts
  library/src/scripts/flyouts/DropDown.tsx
  library/src/scripts/headers/mebox/pieces/MeBoxDropDownItemList.tsx
  library/src/scripts/headers/mebox/pieces/NotificationsContents.tsx
  library/src/scripts/headers/mebox/pieces/UserDropDownContents.tsx
  library/src/scripts/headers/mebox/pieces/UserDropDownContext.tsx
  library/src/scripts/headers/mebox/pieces/UserDropdown.tsx
  library/src/scripts/headers/pieces/MobileDropDown.tsx
  library/src/scripts/headers/titleBarStyles.ts
  library/src/scripts/layout/bodyStyles.ts
  library/src/scripts/layout/frame/FrameBody.tsx
  library/src/scripts/layout/frame/FrameFooter.tsx
  library/src/scripts/layout/frame/FrameHeader.tsx
  library/src/scripts/layout/frame/FrameHeaderWithAction.tsx
  library/src/scripts/layout/frame/frameBodyStyles.ts
  library/src/scripts/layout/frame/frameFooterStyles.ts
  library/src/scripts/layout/frame/frameHeaderStyles.ts
  library/src/scripts/layout/frame/frameStyles.ts
  library/src/scripts/layout/pageHeadingStyles.tsx
  library/src/scripts/layout/panelAreaStyles.ts
  library/src/scripts/modal/ModalConfirm.tsx
  library/src/scripts/routing/links/backLinkStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/styleHelpers.ts
  library/src/scripts/styles/textUtils.ts
  library/src/scripts/styles/typographyStyles.ts
Labels: Priority: Blocker

#8845 Fixing back link positioning issues and close button alignment
  library/src/scripts/features/subcommunities/subcommunityListStyles.ts
  library/src/scripts/headers/pieces/MobileDropDown.tsx
  library/src/scripts/icons/common.tsx
  library/src/scripts/layout/Heading.tsx
  library/src/scripts/layout/PageHeading.tsx
  library/src/scripts/layout/frame/FrameHeader.tsx
  library/src/scripts/layout/frame/frameHeaderStyles.ts
  library/src/scripts/layout/pageHeadingContext.tsx
  library/src/scripts/layout/pageHeadingStyles.tsx
  library/src/scripts/navigation/siteNavStyles.ts
  library/src/scripts/routing/links/backLinkStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
Labels: Priority: Blocker

#8851 Moved browser specific styles into "bodyStyles"
  library/src/scripts/content/Sentence.tsx
  library/src/scripts/features/search/IndependentSearch.tsx
  library/src/scripts/features/search/SearchBar.tsx
  library/src/scripts/features/search/searchBarStyles.ts
  library/src/scripts/flyouts/dropDownStyles.ts
  library/src/scripts/headers/mebox/pieces/CompactSearch.tsx
  library/src/scripts/headers/titleBarStyles.ts
  library/src/scripts/layout/bodyStyles.ts
  library/src/scripts/layout/panelLayoutStyles.ts
  library/src/scripts/splash/Splash.tsx
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/styleHelpers.ts
Labels: Priority: Blocker

#8852 Add styling and wireup for editor placeholder
  library/src/scripts/content/userContentStyles.ts
  plugins/rich-editor/src/scripts/editor/EditorContent.tsx
  plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
  plugins/rich-editor/src/scripts/editor/richEditorVariables.ts
Labels: Priority: Blocker

#8867 Add explicit rich editor scrolling container class and remove analytics setup in bootstrap
  library/src/scripts/bootstrap.ts
  plugins/rich-editor/src/scripts/editor/ForumEditor.tsx
  plugins/rich-editor/src/scripts/quill/ClipboardModule.ts
Labels: Priority: Blocker

#8866 Add Analytics Client interface and stub
  bootstrap.php
  library/Vanilla/Analytics/ActionConstants.php
  library/Vanilla/Analytics/Client.php
  library/Vanilla/Contracts/Analytics/ClientInterface.php
Labels: Priority: Blocker

#8863 Fix error handling in entry AJAX forms
  applications/dashboard/controllers/class.entrycontroller.php
  applications/dashboard/js/password.js
  applications/dashboard/views/entry/auth/password.php
  applications/dashboard/views/entry/connect.php
  applications/dashboard/views/entry/connecterror.php
  applications/dashboard/views/entry/emailconfirm.php
  applications/dashboard/views/entry/emailconfirmrequest.php
  applications/dashboard/views/entry/handshake.php
  applications/dashboard/views/entry/passwordform.php
  applications/dashboard/views/entry/passwordrequest.php
  applications/dashboard/views/entry/passwordreset.php
  applications/dashboard/views/entry/registerapproval.php
  applications/dashboard/views/entry/registerbasic.php
  applications/dashboard/views/entry/registerclosed.php
  applications/dashboard/views/entry/registerinvitation.php
  applications/dashboard/views/entry/signin.php
  applications/dashboard/views/entry/signin2.php
  applications/dashboard/views/entry/signout.php
  js/global.js
  js/library/jquery.gardenhandleajaxform.js
Labels: Release: BC Break
