Repository vanilla/vanilla, pull requests merged in 2019-12, with the labels that each got.

#9798 Fixed breadcrumb and categories page spacing
  library/src/scripts/forms/select/SelectBox.tsx
  library/src/scripts/forms/select/selectBoxStyles.ts
  library/src/scripts/layout/PanelLayout.tsx
  library/src/scripts/layout/panelLayoutStyles.ts
Labels: Priority: Blocker

#9792 Storybook titleBar variations
  library/src/scripts/__tests__/testStoreState.ts
  library/src/scripts/features/users/userModel.ts
  library/src/scripts/headers/TitleBar.tsx
  library/src/scripts/headers/titeBar.story.tsx
  library/src/scripts/headers/titleBarStoryLogo.png
Labels: Status: WIP

#9791 Add ability to add link tags to Vanilla\Web\Page
  library/Vanilla/Site/SiteSectionModel.php
  library/Vanilla/Web/Page.php
  resources/views/default-master.twig
  tests/Library/Vanilla/Web/PageTest.php
  tests/MinimalContainerTestCase.php
  tests/fixtures/src/PageFixture.php
Labels: Priority: Blocker

#9796 Add `imageUploadReact` to `Gdn_Form`
  applications/dashboard/controllers/class.settingscontroller.php
  applications/dashboard/src/scripts/entries/admin.tsx
  applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx
  applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
  applications/dashboard/views/modules/configuration.php
  library/Vanilla/Web/TwigFormWrapper.php
  library/core/class.form.php
  library/src/scripts/AppContext.tsx
  library/src/scripts/utility/componentRegistry.tsx
  tests/Library/Core/FormTest.php
  tests/MinimalContainerTestCase.php
Labels: Priority: Blocker

#9808 Move general functions with dependencies to new framework functions file
  composer.json
  library/core/functions.framework.php
  library/core/functions.general.php
Labels: Priority: Blocker

#9829 Remove fulltext indexes from Vanilla tables
  applications/vanilla/settings/structure.php
Labels: Status: Needs Backport

#9832 Bump up the space available to build storybook.
  package.json
Labels: Domain: Build Process, Type: Technical Debt

#9812 Add tests for functions.general
  library/core/functions.framework.php
  library/core/functions.general.php
  tests/Library/Core/AbsoluteSourceTest.php
  tests/Library/Core/ArrayHasValueTest.php
  tests/Library/Core/ArrayKeyExistsITest.php
  tests/Library/Core/ArraySearchITest.php
  tests/Library/Core/AttributeTest.php
  tests/Library/Core/BetterRandomStringTest.php
  tests/Library/Core/BuildUrlTest.php
  tests/Library/Core/CalculateNumberOfPagesTest.php
  tests/Library/Core/ChangeBaseNameTest.php
  tests/Library/Core/CheckUtf8Test.php
  tests/Library/Core/ChrUtf8Test.php
  tests/Library/Core/CombinePathsTest.php
  tests/Library/Core/ConcatSepTest.php
  tests/Library/Core/DateCompareTest.php
  tests/Library/Core/DebugMethodTest.php
  tests/Library/Core/DebugTest.php
  tests/Library/Core/DeprecatedTest.php
  tests/Library/Core/DomGetContentTest.php
  tests/Library/Core/DomGetImagesTest.php
  tests/Library/Core/ExplodeTrimTest.php
  tests/Library/Core/ForceBoolTest.php
  tests/Library/Core/ForceIPv4Test.php
  tests/Library/Core/ForeignIDHashTest.php
  tests/Library/Core/GetAllMentionsTest.php
  tests/Library/Core/GetConnectionStringTest.php
  tests/Library/Core/GetValueRTest.php
  tests/Library/Core/HtmlEntityDecodeTest.php
  tests/Library/Core/ImplodeAssocTest.php
  tests/Library/Core/InArrayITest.php
  tests/Library/Core/InSubArrayTest.php
  tests/Library/Core/IpEncodeDecodeNonRecursiveTest.php
  tests/Library/Core/IsTimestampTest.php
  tests/Library/Core/IsUrlTest.php
  tests/Library/Core/OffsetLimitTest.php
  tests/Library/Core/PageNumberTest.php
  tests/Library/Core/PrefixStringTest.php
  tests/Library/Core/RandomStringTest.php
  tests/Library/Core/RemoveKeysFromNestedArrayTest.php
  tests/Library/Core/SafePrintTest.php
  tests/Library/Core/SetValueTest.php
  tests/Library/Core/SliceParagraphTest.php
  tests/Library/Core/SliceStringTest.php
  tests/Library/Core/SlugifyTest.php
  tests/Library/Core/StringBeginsWithTest.php
  tests/Library/Core/StringEndsWithTest.php
  tests/Library/Core/StringIsNullOrEmptyTest.php
  tests/Library/Core/Write_ini_stringTest.php
Labels: Status: WIP

#9797 Merge hero image plugin into core
  applications/dashboard/controllers/class.settingscontroller.php
  applications/dashboard/models/BannerImageModel.php
  applications/dashboard/tests/BannerImageModelTest.php
  applications/vanilla/settings/structure.php
  applications/vanilla/tests/HeroImageMigrateTest.php
  applications/vanilla/views/vanillasettings/editcategory.twig
  library/SmartyPlugins/function.banner_image_url.php
  library/SmartyPlugins/function.hero_image_link.php
  library/Vanilla/AliasLoader.php
  plugins/heroimage/.editorconfig
  plugins/heroimage/README.md
  plugins/heroimage/addon.json
  plugins/heroimage/class.heroimage.plugin.php
  plugins/heroimage/hero_image.png
  themes/keystone/KeystoneThemeHooks.php
  themes/keystone/views/customStyles.twig
  themes/keystone/views/default.master.tpl
Labels: Release: DB Update

#9843 Fix missing style-compat.css in sub-communities.
  library/Vanilla/Web/Asset/LegacyAssetModel.php
Labels: Status: Needs Backport

#9848 Add foundation theme
  .gitignore
  applications/dashboard/controllers/api/ThemesApiSchemes.php
  applications/dashboard/controllers/class.profilecontroller.php
  applications/dashboard/views/modules/me.php
  applications/dashboard/views/profile/user-header.twig
  applications/dashboard/views/profile/user.php
  bootstrap.php
  build/scripts/configs/makeBaseConfig.ts
  build/scripts/options.ts
  build/scripts/utility/EntryModel.ts
  library/SmartyPlugins/function.breadcrumbs.php
  library/Vanilla/Models/FsThemeProvider.php
  library/Vanilla/Models/SiteMeta.php
  library/Vanilla/Models/ThemePreloadProvider.php
  library/Vanilla/Theme/ThemeFeatures.php
  library/Vanilla/Theme/TwigAsset.php
  library/Vanilla/Utility/InstanceValidatorSchema.php
  library/Vanilla/Web/MasterView.twig
  library/Vanilla/Web/MasterViewRenderer.php
  library/Vanilla/Web/Page.php
  library/Vanilla/Web/PageHead.php
  library/Vanilla/Web/PageHead.twig
  library/Vanilla/Web/PageHeadInterface.php
  library/Vanilla/Web/PageHeadProxyTrait.php
  library/Vanilla/Web/ThemedPage.php
  library/Vanilla/Web/TwigEnhancer.php
  library/Vanilla/Web/TwigRenderTrait.php
  library/core/class.controller.php
  library/core/class.gdn.php
  library/src/scripts/theming/ThemeProvider.tsx
  package.json
  resources/views/default-master.twig
  tests/Bootstrap.php
  tests/Library/Vanilla/Theme/TwigAssetTest.php
  tests/Library/Vanilla/Web/PageHeadTest.php
  tests/Library/Vanilla/Web/PageTest.php
  tests/Library/Vanilla/Web/TwigEnhancerTest.php
  tests/fixtures/src/PageFixture.php
  themes/foundation/FoundationThemeHooks.php
  themes/foundation/README.md
  themes/foundation/addon.json
  themes/foundation/assets/footer.twig
  themes/foundation/assets/styles.css
  themes/foundation/design/images/vanilla-logo.svg
  themes/foundation/mobile.png
  themes/foundation/package.json
  themes/foundation/screenshot.png
  themes/foundation/settings/configuration.php
  themes/foundation/src/scripts/entries/forum.tsx
  themes/foundation/src/scss/_herobanner.scss
  themes/foundation/src/scss/_themeoptions.scss
  themes/foundation/src/scss/_variables.scss
  themes/foundation/src/scss/custom.scss
  themes/foundation/views/layout.default.twig
  themes/foundation/views/layout.home.twig
  themes/foundation/yarn.lock
  yarn.lock
Labels: Priority: Blocker
