Repository vanilla/vanilla, pull requests merged in 2019-11, with the labels that each got.

#9563 Add dashboard image upload in react
  applications/dashboard/src/scripts/forms/0-SimpleForm.story.tsx
  applications/dashboard/src/scripts/forms/DashboardFormGroup.tsx
  applications/dashboard/src/scripts/forms/DashboardFormLabel.tsx
  applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx
  applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
  library/src/scripts/apiv2.ts
  library/src/scripts/forms/buttonStyles.ts
Labels: Priority: Blocker

#9603 Fixed styles for react based dashboard form elements
  applications/dashboard/src/scripts/forms/DashboardFormListStyles.ts
  applications/dashboard/src/scripts/forms/DashboardImageUpload.tsx
  applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
  applications/dashboard/src/scripts/forms/DashboardInput.tsx
  applications/dashboard/src/scripts/forms/DashboardRadioButton.tsx
  applications/dashboard/src/scripts/forms/DashboardSelect.tsx
  library/src/scripts/features/search/searchBarStyles.ts
  library/src/scripts/flyouts/dropDownStyles.ts
  library/src/scripts/forms/RadioButton.tsx
  library/src/scripts/forms/buttonStyles.ts
  library/src/scripts/forms/checkRadioStyles.ts
  library/src/scripts/forms/select/SelectOne.tsx
  library/src/scripts/layout/frame/FrameFooter.tsx
  library/src/scripts/layout/frame/frameBodyStyles.ts
  library/src/scripts/layout/frame/frameFooterStyles.ts
  library/src/scripts/layout/frame/frameStyles.ts
  library/src/scripts/modal/modalStyles.ts
Labels: Priority: Blocker

#9505 Update HTML format to normalize HTML with consistent classes
  .gitignore
  library/Vanilla/Formatting/Formats/HtmlFormat.php
  tests/fixtures/formats/bbcode/block-formatting/output-excerpt.txt
  tests/fixtures/formats/bbcode/block-formatting/output.html
  tests/fixtures/formats/bbcode/block-formatting/output.txt
  tests/fixtures/formats/bbcode/embeds/output.html
  tests/fixtures/formats/html/inline-formatting/input.html
  tests/fixtures/formats/html/inline-formatting/output.html
  tests/fixtures/formats/html/inline-formatting/output.txt
  tests/fixtures/formats/html/paragraph-formats/input.html
  tests/fixtures/formats/html/paragraph-formats/output-excerpt.txt
  tests/fixtures/formats/html/paragraph-formats/output.html
  tests/fixtures/formats/html/paragraph-formats/output.txt
  tests/fixtures/formats/markdown/paragraph-formatting/output-excerpt.txt
  tests/fixtures/formats/markdown/paragraph-formatting/output.html
  tests/fixtures/formats/markdown/xss/output.html
  tests/fixtures/formats/wysiwyg/paragraph-formats/input.html
  tests/fixtures/formats/wysiwyg/paragraph-formats/output-excerpt.txt
  tests/fixtures/formats/wysiwyg/paragraph-formats/output.html
  tests/fixtures/formats/wysiwyg/paragraph-formats/output.txt
Labels: Status: Hold

#9569 Announcements: Add indices to Discussion table
  applications/vanilla/settings/structure.php
Labels: Release: DB Update

#9630 Fix editor paragraph menu tabs only appearing when open/active
  plugins/rich-editor/src/scripts/menuBar/paragraph/tabs/ParagraphMenuBarTab.tsx
Labels: Status: Needs Backport

#9648 Improve focusing behaviour in modals
  applications/dashboard/src/scripts/forms/DashboardSelect.tsx
  library/src/scripts/forms/select/SelectOne.tsx
  library/src/scripts/modal/Modal.tsx
Labels: Priority: Blocker

#9685 PHPmas 7.2
  .circleci/config.yml
  composer.json
  composer.lock
  environment.php
Labels: Release: BC Break

#9684 Make name optional for SelectBox
  library/src/scripts/forms/select/SelectBox.tsx
  library/src/scripts/messages/messageStyles.ts
Labels: Priority: Blocker

#9681 Demo Feedback - Visual bugs
  library/src/scripts/flyouts/dropDownStyles.ts
  library/src/scripts/forms/select/SelectBox.tsx
  library/src/scripts/forms/select/selectBoxStyles.ts
  library/src/scripts/headers/TitleBar.tsx
  library/src/scripts/headers/mebox/pieces/meBoxStyles.ts
  library/src/scripts/headers/titleBarStyles.ts
  library/src/scripts/icons/common.tsx
  library/src/scripts/icons/iconClasses.ts
  library/src/scripts/layout/frame/frameStyles.ts
Labels: Priority: Blocker
