Repository vanilla/vanilla, pull requests merged in 2019-06, with the labels that each got.

#8890 Fix forum post editing not working with Rich Editor
  plugins/rich-editor/src/scripts/editor/EditorContent.tsx
Labels: Status: Needs Backport

#8888 Fix issues with the phing build process
  applications/conversations/addon.json
  applications/dashboard/addon.json
  applications/vanilla/addon.json
  bin/scripts/buildRelease.js
  build/build.xml
  build/package-exclude.txt
  environment.php
Labels: Status: Needs Backport

#8899 Rollback garden-http to v1
  composer.json
  composer.lock
  library/Vanilla/PageScraper.php
  tests/Library/Vanilla/PageScraperTest.php
  tests/fixtures/src/PageScraper.php
Labels: Status: Needs Backport

#8258 Delete Gdn_Factory, ISingleton, and some related deprecated methods/classes
  library/core/class.controller.php
  library/core/class.factory.php
  library/core/class.gdn.php
  library/core/interface.isingleton.php
Labels: Release: BC Break

#8901 Fix comment post editing in the forum
  library/src/scripts/dom/domUtils.test.ts
  library/src/scripts/dom/domUtils.tsx
Labels: Status: Needs Backport

#8910 Fix some case sensitivity issues with emoji extender
  .gitignore
  plugins/emojiextender/EmojiExtenderPlugin.php
  plugins/emojiextender/addon.json
Labels: Status: Needs Backport

#8953 Backports for release/2019.007
  library/Vanilla/Web/CacheControlMiddleware.php
  library/core/class.controller.php
  library/core/class.oauth2.php
  library/src/scripts/utility/utils.ts
  plugins/emojiextender/EmojiExtenderPlugin.php
  plugins/googlesignin/addon.json
  plugins/rich-editor/src/scripts/__tests__/quillUtils.ts
  plugins/rich-editor/src/scripts/__tests__/quillUtils.tsx
  plugins/rich-editor/src/scripts/editor/EditorContent.test.tsx
  plugins/rich-editor/src/scripts/editor/EditorContent.tsx
Labels: Status: WIP

#8952 Add discussion data when calling categroydropdown
  applications/vanilla/controllers/class.moderationcontroller.php
  applications/vanilla/views/moderation/confirmdiscussionmoves.php
Labels: Status: WIP

#8978 Split front-end style helper functions into multiple files and fixed regression bugs
  library/src/scripts/content/Count.tsx
  library/src/scripts/content/countStyles.ts
  library/src/scripts/forms/buttonStyles.ts
  library/src/scripts/layout/frame/frameHeaderStyles.ts
  library/src/scripts/splash/Splash.tsx
  library/src/scripts/splash/splashStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/shadowHelpers.ts
  library/src/scripts/styles/styleHelpers.ts
  library/src/scripts/styles/styleHelpersAnimation.ts
  library/src/scripts/styles/styleHelpersBackgroundStyling.ts
  library/src/scripts/styles/styleHelpersBorders.ts
  library/src/scripts/styles/styleHelpersButtons.ts
  library/src/scripts/styles/styleHelpersColors.ts
  library/src/scripts/styles/styleHelpersDropShadow.ts
  library/src/scripts/styles/styleHelpersFeedback.ts
  library/src/scripts/styles/styleHelpersLinks.ts
  library/src/scripts/styles/styleHelpersMargin.ts
  library/src/scripts/styles/styleHelpersPositioning.ts
  library/src/scripts/styles/styleHelpersReset.ts
  library/src/scripts/styles/styleHelpersSpinner.ts
  library/src/scripts/styles/styleHelpersTypography.ts
  library/src/scripts/styles/styleHelpersVisibility.ts
  library/src/scripts/styles/styleHelpersfPadding.ts
  library/src/scss/utility/_icons.scss
  plugins/rich-editor/src/scripts/editor/richEditorClasses.ts
  plugins/rich-editor/src/scripts/editor/richEditorVariables.ts
  plugins/rich-editor/src/scripts/menuBar/paragraph/ParagraphMenusBarToggle.tsx
  plugins/rich-editor/src/scripts/toolbars/pieces/insertLinkClasses.ts
Labels: Priority: Blocker

#8970 Implement CSP 'frame-ancestors' header for Gdn_Controller
  applications/dashboard/controllers/StaticContentController.php
  applications/dashboard/settings/structure.php
  applications/dashboard/views/staticcontent/container.twig
  library/Vanilla/Web/ContentSecurityPolicy/ContentSecurityPolicyModel.php
  library/Vanilla/Web/ContentSecurityPolicy/DefaultContentSecurityPolicyProvider.php
  library/Vanilla/Web/ContentSecurityPolicyMiddleware.php
  library/core/class.controller.php
Labels: Release: Custom Notes, Release: DB Update, Status: Needs Backport

#8984 Add conditions to show or hide the entry/connect name field.
  applications/dashboard/views/entry/connect.php
Labels: Domain: Authentication
