Repository vanilla/vanilla, pull requests merged in 2020-02, with the labels that each got.

#10046 Fix editor mounting
  packages/vanilla-react-utils/src/mounting.tsx
  plugins/rich-editor/src/scripts/mountEditor.tsx
Labels: Status: Needs Backport

#10055 Fix titlebar alignment and collision detection
  library/src/scripts/headers/TitleBar.tsx
Labels: Status: Backported

#10064 Fix banner overflow
  library/src/scripts/banner/banner.story.tsx
  library/src/scripts/banner/bannerStyles.ts
  library/src/scripts/layout/components/containerStyles.ts
Labels: Status: Backported

#10072 Update categories page to load a CategoryID from the current site section
  applications/vanilla/controllers/class.categoriescontroller.php
  library/Vanilla/Contracts/Site/SiteSectionInterface.php
  library/Vanilla/Site/DefaultSiteSection.php
  tests/fixtures/src/MockSiteSection.php
Labels: Priority: Blocker, Status: Backported

#10076 Fix various theming issues in new system
  applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
  library/src/scripts/banner/bannerStyles.ts
  library/src/scripts/features/tiles/tileStyles.ts
Labels: Status: Needs Backport

#10085 Implement theming improvements
  library/src/scripts/banner/Banner.tsx
  library/src/scripts/banner/bannerStyles.ts
  library/src/scripts/features/tiles/Tiles.tsx
  library/src/scripts/features/tiles/tilesStyles.ts
  library/src/scripts/headers/TitleBar.tsx
  library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
  library/src/scripts/homeWidget/HomeWidgetContainer.tsx
  library/src/scripts/layout/components/Container.tsx
  library/src/scripts/layout/components/containerStyles.ts
  library/src/scripts/styles/styleHelpersSpacing.ts
  library/src/scripts/styles/styleUtils.ts
  library/src/scripts/theming/loadThemeFonts.ts
Labels: Status: Backported

#10129 Fix PermissionModel
  applications/dashboard/models/class.permissionmodel.php
Labels: Priority: Blocker
