Repository vanilla/vanilla, pull requests merged in 2020-06, with the labels that each got.

#10675 Fix bad name on the MySQLDriverTest
  tests/Library/Database/MySQLDriverTest.php
Labels: merge when passing

#10679 Tweak some types for home widgets
  library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
  library/src/scripts/homeWidget/HomeWidgetItem.styles.ts
Labels: Priority: Blocker

#10703 Fixed a few imports for HTMLUtils
  applications/vanilla/views/categories/helper_functions.php
  applications/vanilla/views/discussion/discussion.php
  applications/vanilla/views/modules/discussionfilter.php
  applications/vanilla/views/modules/helper_functions.php
Labels: Priority: Blocker

#10708 Accessibility Improvements - aria labels, duplicate IDs, alt text, discernible text, landmarks
  applications/conversations/js/conversations.js
  applications/dashboard/models/class.activitymodel.php
  applications/dashboard/src/scripts/legacy/atwho.ts
  applications/dashboard/views/modules/dropdown.php
  applications/vanilla/js/tagging.js
  applications/vanilla/views/discussions/helper_functions.php
  applications/vanilla/views/modules/helper_functions.php
  applications/vanilla/views/post/comment.php
  js/library/jquery.atwho.js
  js/library/jquery.autosize.min.js
  js/library/jquery.tokeninput.js
  library/Vanilla/Utility/HtmlUtils.php
  library/src/scripts/@types/api/notifications.ts
  library/src/scripts/embeddedContent/ImageEmbed.tsx
  library/src/scripts/flyouts/DropDown.tsx
  library/src/scripts/flyouts/DropDownContents.tsx
  library/src/scripts/flyouts/FlyoutToggle.tsx
  library/src/scripts/flyouts/StoryExampleDropDown.tsx
  library/src/scripts/flyouts/StoryExampleDropDownNotifications.tsx
  library/src/scripts/gdn.ts
  library/src/scripts/headers/mebox/pieces/MeBoxDropDownItem.tsx
  library/src/scripts/headers/mebox/pieces/MessagesContents.tsx
  library/src/scripts/headers/mebox/pieces/NotificationsContents.tsx
  library/src/scripts/headers/mebox/pieces/StorybookExampleNotificationsDropDown.tsx
  library/src/scripts/headers/mebox/pieces/TitleBarNav.tsx
  library/src/scripts/headers/mebox/pieces/UserPhoto.tsx
  library/src/scripts/icons/titleBar.tsx
  library/src/scripts/layout/frame/FrameHeaderMinimal.tsx
  library/src/scripts/utility/appUtils.tsx
  packages/vanilla-theme-core/scss/patches/_vanillicon-general-patches.scss
  plugins/rich-editor/src/scripts/editor/Editor.tsx
  plugins/rich-editor/src/scripts/editor/EditorEmbedBar.tsx
  plugins/rich-editor/src/scripts/editor/ForumEditor.tsx
  plugins/rich-editor/src/scripts/entries/forum.ts
  plugins/rich-editor/src/scripts/flyouts/EmbedFlyout.tsx
  plugins/rich-editor/src/scripts/flyouts/EmojiFlyout.tsx
  plugins/rich-editor/src/scripts/flyouts/pieces/EmojiPicker.tsx
  plugins/rich-editor/src/scripts/flyouts/pieces/Flyout.tsx
  plugins/rich-editor/src/scripts/mountEditor.tsx
Labels: Priority: Blocker

#10740 Fix encoding on file names.
  library/Vanilla/UploadedFile.php
  tests/Library/Vanilla/UploadedFileTest.php
Labels: Status: Needs Backport

#10770 Forward port various backports
  applications/dashboard/models/BannerImageModel.php
  applications/dashboard/models/class.activitymodel.php
  bootstrap.php
  library/core/class.authenticationprovidermodel.php
Labels: Priority: High

#10768 Move LogDecorator to end of bootstrapping
  bootstrap.php
Labels: Priority: High

#10779 Update jsConnect to 3.2.1
  composer.json
  composer.lock
Labels: Priority: High

#10788 Fix json processor breaking delete operations
  library/Vanilla/Database/Operation/JsonFieldProcessor.php
  tests/Library/Vanilla/Models/ModelTest.php
  tests/Library/Vanilla/Models/PipelineModelTest.php
Labels: Priority: Blocker

#10807 Bypass mods from image upload restrictions
  applications/dashboard/controllers/api/MediaApiController.php
  applications/dashboard/models/class.mediamodel.php
  applications/vanilla/views/vanillasettings/posting.php
  library/Vanilla/UploadedFile.php
  tests/Library/Vanilla/UploadedFileTest.php
Labels: Status: WIP
