Repository vanilla/vanilla, pull requests merged in 2020-04, with the labels that each got.

#10397 Extend CurrentUserFieldProcessor to respect operation MODE_IMPORT
  applications/dashboard/settings/structure.php
  library/Vanilla/Database/Operation/CurrentUserFieldProcessor.php
  tests/Library/Vanilla/Database/CurrentUserFieldProcessorTest.php
Labels: Release: DB Update

#10410 Fix banner search strip positioning and home widget background
  library/src/scripts/banner/Banner.tsx
  library/src/scripts/banner/bannerStyles.ts
  library/src/scripts/homeWidget/HomeWidgetContainer.styles.ts
Labels: Status: Needs Backport

#10391 Foundation bookmarks
  applications/dashboard/src/scripts/compatibilityStyles/compatibilityIcons.tsx
  applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/index.ts
  applications/dashboard/src/scripts/entries/forum.tsx
  library/src/scripts/icons/common.tsx
  library/src/scripts/icons/iconClasses.ts
  library/src/scripts/icons/icons.story.tsx
  library/src/scripts/loaders/loaderStyles.ts
  library/src/scripts/styles/styleHelpersBackgroundStyling.ts
Labels: Priority: Blocker

#10409 Theme Editor : External Fonts
  applications/dashboard/design/admin.css
  applications/dashboard/design/admin.css.map
  applications/dashboard/scss/src/_media.scss
  applications/dashboard/src/scripts/compatibilityStyles/compatibilityIcons.tsx
  applications/dashboard/src/scripts/entries/admin.tsx
  library/src/scripts/forms/FormToggle.styles.ts
  library/src/scripts/forms/FormToggle.tsx
  library/src/scripts/forms/InputTextBlock.tsx
  library/src/scripts/forms/inputStyles.ts
  library/src/scripts/forms/themeEditor/CustomFontFamily.tsx
  library/src/scripts/forms/themeEditor/CustomFontUrl.tsx
  library/src/scripts/forms/themeEditor/GoogleFontDropdown.tsx
  library/src/scripts/forms/themeEditor/ThemeBuilder.styles.ts
  library/src/scripts/forms/themeEditor/ThemeBuilderBlock.tsx
  library/src/scripts/forms/themeEditor/ThemeBuilderBreakpoints.tsx
  library/src/scripts/forms/themeEditor/ThemeBuilderContext.tsx
  library/src/scripts/forms/themeEditor/ThemeBuilderFontBlock.tsx
  library/src/scripts/forms/themeEditor/ThemeBuilderRevert.tsx
  library/src/scripts/forms/themeEditor/ThemeColorPicker.tsx
  library/src/scripts/forms/themeEditor/ThemeDropDown.tsx
  library/src/scripts/forms/themeEditor/ThemeEditor.story.tsx
  library/src/scripts/forms/themeEditor/ThemeInfoTooltip.tsx
  library/src/scripts/forms/themeEditor/ThemeInputNumber.tsx
  library/src/scripts/forms/themeEditor/ThemeInputText.tsx
  library/src/scripts/forms/themeEditor/ThemeToggle.tsx
  library/src/scripts/forms/themeEditor/themeInputText.styles.ts
  library/src/scripts/icons/common.tsx
  library/src/scripts/icons/iconClasses.ts
  library/src/scripts/icons/icons.story.tsx
  library/src/scripts/routing/links/SmartLink.tsx
  library/src/scripts/storybook/StoryBookStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/styleHelpersTypography.ts
  library/src/scripts/styles/typographyStyles.ts
  library/src/scripts/theming/loadThemeFonts.ts
  library/src/scripts/theming/themeReducer.ts
Labels: Priority: Blocker

#10447 Revert tag cloud tag
  applications/dashboard/src/scripts/compatibilityStyles/forumTagStyles.ts
  applications/vanilla/modules/class.tagmodule.php
Labels: Status: Needs Backport

#10472 Demo Feedback and clean up
  applications/dashboard/design/admin.css
  applications/dashboard/design/admin.css.map
  applications/dashboard/design/style-compat.css
  applications/dashboard/design/style-compat.css.map
  applications/dashboard/scss/style-compat.scss
  applications/dashboard/src/scripts/compatibilityStyles/compatibilityIcons.tsx
  applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts
  library/src/scripts/embeddedContent/EmbedRenderError.tsx
  library/src/scripts/features/swagger/SwaggerIcon.tsx
  library/src/scripts/icons/common.tsx
  library/src/scripts/icons/fileTypes.tsx
  library/src/scripts/icons/iconStyles.ts
  library/src/scripts/icons/icons.story.tsx
  library/src/scripts/icons/revision.tsx
  library/src/scripts/icons/titleBar.tsx
  library/src/scripts/layout/PageHeading.tsx
  library/src/scripts/layout/pageTitleStyles.tsx
  library/src/scripts/sectioning/Tabs.tsx
  library/src/scripts/sectioning/tabStyles.ts
  library/src/scripts/storybook/StoryBookStyles.ts
  library/src/scripts/styles/styleHelpersSpacing.ts
  library/src/scripts/theming/ThemePreviewCard.tsx
  library/src/scss/utility/_scaffolding.scss
Labels: Priority: Blocker

#10520 Implement media rehosting in UploadedFile
  applications/dashboard/controllers/api/MediaApiController.php
  applications/dashboard/controllers/api/UsersApiController.php
  applications/dashboard/models/class.mediamodel.php
  applications/dashboard/settings/structure.php
  applications/dashboard/tests/MediaModelTest.php
  composer.json
  library/Garden/Web/Data.php
  library/Vanilla/Contracts/Web/FileUploadHandler.php
  library/Vanilla/EmbeddedContent/Embeds/FileEmbed.php
  library/Vanilla/FileUtils.php
  library/Vanilla/Formatting/Attachment.php
  library/Vanilla/Formatting/Formats/HtmlFormat.php
  library/Vanilla/Formatting/Html/Processor/AttachmentHtmlProcessor.php
  library/Vanilla/Models/VanillaMediaSchema.php
  library/Vanilla/UploadedFile.php
  library/Vanilla/Web/Controller.php
  library/core/class.upload.php
  library/core/class.vanillahtmlformatter.php
  tests/APIv2/MediaTest.php
  tests/APIv2/UsersTest.php
  tests/Library/Vanilla/Formatting/Formats/AbstractFormatTestCase.php
  tests/Library/Vanilla/UploadedFileTest.php
  tests/fixtures/formats/html/attachments/input.html
  tests/fixtures/formats/html/attachments/output-attachments.json
  tests/fixtures/formats/html/attachments/output.html
  tests/fixtures/formats/html/attachments/output.txt
  tests/fixtures/src/Formatting/FormatFixture.php
  tests/fixtures/src/TestUploader.php
  tests/phpunit.php
Labels: Release: DB Update
