Repository vanilla/vanilla, pull requests merged in 2020-01, with the labels that each got.

#9922 Fix panel scrolling issues
  library/src/scripts/Router.tsx
  library/src/scripts/layout/panelAreaStyles.ts
  library/src/scripts/layout/panelLayoutStyles.ts
  library/src/scripts/navigation/breadcrumbsStyles.ts
Labels: Status: Needs Backport

#9920 Apply more case-insensitive format checks for rich
  applications/vanilla/controllers/api/CommentsApiController.php
  applications/vanilla/controllers/api/DiscussionsApiController.php
  plugins/rich-editor/RichEditorPlugin.php
  plugins/rich-editor/src/scripts/entries/admin.ts
  plugins/rich-editor/src/scripts/mountEditor.tsx
Labels: Status: Needs Backport

#9925 IE 11 - Bumped up specificity and fixed CSS prop for logo
  packages/vanilla-polyfill/index.js
  themes/theme-boilerplate/src/scss/sections/_header.scss
Labels: Status: Needs Backport

#9930 Allow image transparency when resizing images using GD
  library/Vanilla/ImageResizer.php
Labels: Status: Needs Backport

#9928 Fix breadcrumb scrolling issue
  library/src/scripts/headers/TitleBar.tsx
  library/src/scripts/navigation/breadcrumbsStyles.ts
Labels: Status: Needs Backport

#9952 Update to allow post\patch endpoints to allow assets parameter to be array
  applications/dashboard/controllers/api/ThemesApiSchemes.php
  library/Vanilla/Models/ThemeModel.php
Labels: Priority: Blocker

#9986 Fix analytics events firing incorrectly
  library/src/scripts/Router.tsx
  library/src/scripts/analytics/AnalyticsData.tsx
  library/src/scripts/bootstrap.ts
  library/src/scripts/pageViews/pageViewTracking.spec.ts
  library/src/scripts/pageViews/pageViewTracking.ts
Labels: Status: Needs Backport

#9987 Fix various theming issues
  library/Vanilla/Models/FsThemeProvider.php
  library/src/scripts/features/tiles/tilesStyles.ts
  library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
  library/src/scripts/styles/styleHelpersColors.ts
  tests/APIv2/ThemesTest.php
Labels: Status: Needs Backport

#10002 Exclude unneeded monaco directories
  build/scripts/utility/moduleUtils.ts
Labels: Priority: Blocker

#9985 Add animations and transitions to modals
  applications/dashboard/src/scripts/forms/DashboardImageUploadGroup.tsx
  library/src/scripts/animation/EntranceAnimation.tsx
  library/src/scripts/embeddedContent/ImageEmbed.tsx
  library/src/scripts/embeddedContent/StoryExampleModal.tsx
  library/src/scripts/embeddedContent/StoryExampleModalConfirm.tsx
  library/src/scripts/flyouts/DropDownContents.tsx
  library/src/scripts/flyouts/FlyoutToggle.tsx
  library/src/scripts/headers/mebox/pieces/CompactMeBox.tsx
  library/src/scripts/headers/pieces/MobileDropDown.tsx
  library/src/scripts/headers/pieces/mobileDropDownStyles.ts
  library/src/scripts/modal/Modal.tsx
  library/src/scripts/modal/ModalConfirm.tsx
  library/src/scripts/modal/ModalLoader.tsx
  library/src/scripts/modal/ModalView.tsx
  library/src/scripts/modal/modalStyles.ts
  plugins/rich-editor/src/scripts/editor/pieces/ImageEmbedModal.tsx
Labels: Release: BC Break
