Repository vanilla/vanilla, pull requests merged in 2020-03, with the labels that each got.

#10244 Fix firing PSR-14 user events for users with empty password fields
  applications/dashboard/controllers/api/UsersApiController.php
  applications/dashboard/models/class.usermodel.php
Labels: Status: Needs Backport

#10269 Foundation - Tag styles
  applications/dashboard/src/scripts/compatibilityStyles/discussionStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/fontStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/forumMetaStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/forumTagStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/index.ts
  applications/dashboard/src/scripts/compatibilityStyles/tableStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts
  applications/vanilla/modules/class.tagmodule.php
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/styleHelpersLinks.ts
  library/src/scripts/styles/tagStyles.ts
  packages/vanilla-theme-core/scss/components/_lists.scss
Labels: QA: Needs QA

#10270 Foundation - Fixed titleBar and messages issues
  applications/dashboard/src/scripts/compatibilityStyles/index.ts
  applications/dashboard/src/scripts/compatibilityStyles/messagesStyles.ts
  library/src/scripts/features/search/searchBarStyles.ts
  library/src/scripts/headers/mebox/pieces/compactSearchStyles.ts
  library/src/scripts/headers/titleBarStyles.ts
  packages/vanilla-theme-core/scss/pages/_inbox.scss
Labels: QA: Needs QA

#10268 Foundation - Style updates to search results
  applications/dashboard/src/scripts/compatibilityStyles/forumMetaStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/searchPageStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts
  library/src/scripts/styles/metasStyles.ts
  plugins/rich-editor/src/scripts/editor/richEditorStyles.ts
Labels: Priority: Blocker, QA: Needs QA

#10291 Refactor State Names
  applications/dashboard/src/scripts/compatibilityStyles/forumMetaStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/index.ts
  applications/dashboard/src/scripts/compatibilityStyles/searchPageStyles.ts
  applications/dashboard/src/scripts/compatibilityStyles/textLinkStyles.ts
  library/src/scripts/content/userContentStyles.ts
  library/src/scripts/flyouts/dropDownStyles.ts
  library/src/scripts/forms/buttonStyles.ts
  library/src/scripts/headers/titleBarStyles.ts
  library/src/scripts/headers/vanillaHeaderStyles.ts
  library/src/scripts/homeWidget/HomeWidgetItem.styles.ts
  library/src/scripts/messages/messageStyles.ts
  library/src/scripts/navigation/breadcrumbsStyles.ts
  library/src/scripts/navigation/navLinksStyles.ts
  library/src/scripts/navigation/siteNavStyles.ts
  library/src/scripts/styles/globalStyleVars.ts
  library/src/scripts/styles/styleHelpersButtons.ts
  library/src/scripts/styles/styleHelpersLinks.ts
  library/src/scripts/styles/tagStyles.ts
  plugins/rich-editor/src/scripts/flyouts/pieces/insertEmojiClasses.ts
Labels: Priority: Blocker

#10306 Fix path of new message button to be new message and not inbox
  library/src/scripts/headers/mebox/pieces/MessagesContents.tsx
Labels: Type: Bug
